Song selection screen
bickoSiTiEff/Raspio pull request #19
Opened 2021-06-15 11:53 UTC by CallMeAlasca

Linked Task: #RASPIO-31

2021-06-15 14:47 UTC, profiluefter requested changes

2021-06-15 14:47 UTC, profiluefter commented on app/app/src/main/java/me/bickositieff/raspio/ui/playlist/SongAdapter.kt
> +open class SongAdapter(
I don't think this is still needed, is it?
```suggestion
class SongAdapter(
```

2021-06-15 14:47 UTC, profiluefter commented on app/app/src/main/java/me/bickositieff/raspio/ui/songSelect/SongSelectFragment.kt
> +    private lateinit var mAdapter: SongSelectAdapter
There's no reason for this to be an instance variable. Content is updated via LiveData

2021-06-15 14:47 UTC, profiluefter commented on app/app/src/main/java/me/bickositieff/raspio/ui/songSelect/SongSelectViewModel.kt
> +            kotlinx.coroutines.delay(1000)
```suggestion
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import me.bickositieff.raspio.generated.api.LibraryApi
import me.bickositieff.raspio.generated.api.PlaylistApi
import me.bickositieff.raspio.generated.models.POSTPlaylistBody
import me.bickositieff.raspio.ui.models.Song

class SongSelectViewModel : ViewModel() {
    val availableSongs = liveData {
        emit(emptyList())
        while (true) {
            emit(LibraryApi.getSongs().body()!!.map { Song(it.path!!, it.title!!, it.artist!!, it.duration!!, null) })
            delay(1000)
```

2021-06-15 14:47 UTC, profiluefter commented on app/app/src/main/res/menu/popup_select_song.xml
> +<menu
very interesting formatting in this file

2021-06-15 14:47 UTC, profiluefter commented on app/app/src/main/res/navigation/mobile_navigation.xml
> +                app:popUpTo="@id/navigation_playlist"/>
popUpTo sets where to go when you navigate back from the selection, so the previous screen (playlist) is already the default.
```suggestion
                app:destination="@id/navigation_song_select"/>
```

2021-06-15 20:00 UTC, SchneckchenAndy approved these changes

2021-06-16 12:50 UTC, profiluefter approved these changes

2021-06-16 12:51 UTC, merged