Playlist Fragment
bickoSiTiEff/Raspio pull request #7
Opened 2021-06-04 23:02 UTC by CallMeAlasca

Linked Task: #RASPIO-15

2021-06-04 23:50 UTC, profiluefter requested changes
Fragment label should be changed

2021-06-04 23:50 UTC, profiluefter commented on app/app/src/main/java/me/bickositieff/raspio/ui/models/Song.kt
> +    val image: Int?
Will probably not be usable like that but we'll change it when we know how we'll use it

2021-06-04 23:50 UTC, profiluefter commented on app/app/src/main/java/me/bickositieff/raspio/ui/playlist/PlaylistFragment.kt
> +    private lateinit var playlistViewModel: PlaylistViewModel
Could have been initialized using `by viewModel()` (see https://stackoverflow.com/q/56748334/8719698) but results in the same

2021-06-04 23:50 UTC, profiluefter commented on app/app/src/main/res/navigation/mobile_navigation.xml
>              android:label="@string/title_home"
This should probably be changed to playlist or something
```suggestion
            android:label="@string/title_playlist"
```

2021-06-04 23:50 UTC, profiluefter commented on app/app/src/main/res/values/strings.xml
>      <string name="title_home">Home</string>
```suggestion
    <string name="title_playlist">Playlist</string>
```

2021-06-05 14:21 UTC, profiluefter approved these changes

2021-06-05 15:31 UTC, SchneckchenAndy approved these changes

2021-06-05 20:47 UTC, merged